# Introduction to Python Matrices and NumPy

Welcome to this introduction to NumPy, the essential library for numerical computing in Python. This notebook will guide you through creating and manipulating 2D arrays, executing mathematical operations efficiently, and understanding core NumPy functionalities. If you're already familiar with NumPy, feel free to skip this.

### Learning Objectives
After completing this notebook, you will be able to:
- Use Jupyter Notebook effectively.
- Create and manipulate NumPy arrays.
- Apply indexing, slicing, and reshaping techniques.
- Perform mathematical operations and array transformations.
- Stack arrays horizontally and vertically.

## 1. Introduction to Jupyter Notebooks
Jupyter Notebooks are interactive environments that integrate live code, documentation, equations, and visualizations. To execute a code cell, press **Shift + Enter** or click the **Run** button.


In [1]:
# Run the following cell to print "Hello World".
test = "Hello World"
print(test)


Hello World


## 2. Basics of NumPy

NumPy provides powerful tools for handling large datasets efficiently, offering optimized functions for mathematical operations.

### 2.1 Importing NumPy
To use NumPy, import it as follows:

In [7]:
import numpy as np

### 2.2 Advantages of NumPy Arrays
NumPy arrays (ndarrays) are faster, more memory-efficient, and support vectorized operations compared to Python lists.


In [9]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)  # Output: [10 12]

[10 12]


## 3. Creating NumPy Arrays

### 3.1 Using `np.array()`

In [10]:
a = np.array([1, 2, 3])
print(a)  # Output: [1 2 3]

[1 2 3]


### 3.2 Using `np.arange()`

In [11]:
b = np.arange(3)
print(b)  # Output: [0 1 2]

c = np.arange(1, 20, 3)
print(c)  # Output: [1 4 7 10 13 16 19]

[0 1 2]
[ 1  4  7 10 13 16 19]


### 3.3 Using `np.linspace()`

In [12]:
lin_spaced_arr = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr)  # Output: [  0  25  50  75 100]

[  0  25  50  75 100]


### 3.4 Special Arrays

In [13]:
np.ones(3)      # [1. 1. 1.]
np.zeros(3)     # [0. 0. 0.]
np.empty(3)     # Uninitialized values
np.random.rand(3)  # Random values between 0 and 1

array([0.04067224, 0.86065678, 0.20746947])

## 4. Multidimensional Arrays

In [15]:
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


### 4.1 Reshaping Arrays

In [16]:
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])
multi_dim_arr = np.reshape(one_dim_arr, (2,3))
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


### 4.2 Finding Shape and Size

In [17]:
print(multi_dim_arr.ndim)   # Number of dimensions
print(multi_dim_arr.shape)  # Shape (rows, columns)
print(multi_dim_arr.size)   # Total number of elements

2
(2, 3)
6


## 5. Mathematical Operations

### 5.1 Element-wise Operations

In [18]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

print(arr_1 + arr_2)  # Addition
print(arr_1 - arr_2)  # Subtraction
print(arr_1 * arr_2)  # Multiplication

[ 3  7 11]
[1 1 1]
[ 2 12 30]


### 5.2 Broadcasting (Multiplication with Scalars)

In [19]:
vector = np.array([1, 2])
print(vector * 1.6)  # Output: [1.6 3.2]

[1.6 3.2]


## 6. Indexing and Slicing

### 6.1 Indexing

In [20]:
a = np.array([1, 2, 3, 4, 5])
print(a[2])  # Output: 3

3


For 2D arrays:

In [21]:
two_dim = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two_dim[2,1])  # Output: 8

8


### 6.2 Slicing

In [22]:
print(a[1:4])  # Output: [2 3 4]
print(a[:3])   # Output: [1 2 3]
print(a[2:])   # Output: [3 4 5]
print(a[::2])  # Output: [1 3 5]

[2 3 4]
[1 2 3]
[3 4 5]
[1 3 5]


For 2D arrays:

In [23]:
print(two_dim[0:2])  # First two rows
print(two_dim[:,1])  # Second column

[[1 2 3]
 [4 5 6]]
[2 5 8]


## 7. Stacking Arrays

### 7.1 Vertical and Horizontal Stacking

In [24]:
a1 = np.array([[1,1], [2,2]])
a2 = np.array([[3,3], [4,4]])

print(np.vstack((a1, a2)))  # Vertical stacking
print(np.hstack((a1, a2)))  # Horizontal stacking

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


### 7.2 Splitting Arrays

In [25]:
array = np.array([1, 2, 3, 4, 5, 6])
print(np.split(array, 2))  # Split into two equal arrays

[array([1, 2, 3]), array([4, 5, 6])]


## 8. Exercises
Try implementing the following:
- Create a 3x3 matrix filled with random values.
- Extract a submatrix from a given 4x4 matrix.
- Perform matrix multiplication using `np.dot()`.
